# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ title: 'Chicago' }, { title: 'Copenhagen' }])
#   Mayor.create(title: 'Emanuel', city: cities.first)

Article.create(title: "generated through seed.rb", content: "Wayfarers semiotics trust fund ugh, venmo plaid skateboard blog kogi austin +1 helvetica. Slow-carb four dollar toast craft beer poutine authentic typewriter, kinfolk VHS crucifix mustache mumblecore. Echo park ugh single-origin coffee, aesthetic trust fund schlitz YOLO occupy pug pop-up listicle. Portland bespoke poutine twee four dollar toast. Bicycle rights man bun heirloom polaroid, banjo schlitz brooklyn poutine cliche helvetica meditation venmo. Offal sartorial ugh, small batch put a bird on it pug green juice tumblr. 8-bit literally keffiyeh offal master cleanse poutine.

Chambray kale chips dreamcatcher migas pitchfork semiotics. Marfa narwhal bitters post-ironic, dreamcatcher vinyl kickstarter humblebrag. Craft beer kogi trust fund gentrify tattooed. Tilde heirloom cray, wolf banh mi mixtape chia tumblr chillwave next level. Selvage thundercats swag cold-pressed brooklyn squid +1, mlkshk hammock locavore biodiesel. Kitsch meditation selvage fap freegan roof party semiotics, direct trade leggings 3 wolf moon. Lumbersexual helvetica vinyl waistcoat, try-hard iPhone beard small batch gentrify single-origin coffee kitsch trust fund.")


Article.create(title: "generated through seed.rb", content: "Wayfarers semiotics trust fund ugh, venmo plaid skateboard blog kogi austin +1 helvetica. Slow-carb four dollar toast craft beer poutine authentic typewriter, kinfolk VHS crucifix mustache mumblecore. Echo park ugh single-origin coffee, aesthetic trust fund schlitz YOLO occupy pug pop-up listicle. Portland bespoke poutine twee four dollar toast. Bicycle rights man bun heirloom polaroid, banjo schlitz brooklyn poutine cliche helvetica meditation venmo. Offal sartorial ugh, small batch put a bird on it pug green juice tumblr. 8-bit literally keffiyeh offal master cleanse poutine.

Chambray kale chips dreamcatcher migas pitchfork semiotics. Marfa narwhal bitters post-ironic, dreamcatcher vinyl kickstarter humblebrag. Craft beer kogi trust fund gentrify tattooed. Tilde heirloom cray, wolf banh mi mixtape chia tumblr chillwave next level. Selvage thundercats swag cold-pressed brooklyn squid +1, mlkshk hammock locavore biodiesel. Kitsch meditation selvage fap freegan roof party semiotics, direct trade leggings 3 wolf moon. Lumbersexual helvetica vinyl waistcoat, try-hard iPhone beard small batch gentrify single-origin coffee kitsch trust fund.")


Article.create(title: "generated through seed.rb", content: "Wayfarers semiotics trust fund ugh, venmo plaid skateboard blog kogi austin +1 helvetica. Slow-carb four dollar toast craft beer poutine authentic typewriter, kinfolk VHS crucifix mustache mumblecore. Echo park ugh single-origin coffee, aesthetic trust fund schlitz YOLO occupy pug pop-up listicle. Portland bespoke poutine twee four dollar toast. Bicycle rights man bun heirloom polaroid, banjo schlitz brooklyn poutine cliche helvetica meditation venmo. Offal sartorial ugh, small batch put a bird on it pug green juice tumblr. 8-bit literally keffiyeh offal master cleanse poutine.

Chambray kale chips dreamcatcher migas pitchfork semiotics. Marfa narwhal bitters post-ironic, dreamcatcher vinyl kickstarter humblebrag. Craft beer kogi trust fund gentrify tattooed. Tilde heirloom cray, wolf banh mi mixtape chia tumblr chillwave next level. Selvage thundercats swag cold-pressed brooklyn squid +1, mlkshk hammock locavore biodiesel. Kitsch meditation selvage fap freegan roof party semiotics, direct trade leggings 3 wolf moon. Lumbersexual helvetica vinyl waistcoat, try-hard iPhone beard small batch gentrify single-origin coffee kitsch trust fund.")


Article.create(title: "generated through seed.rb", content: "Wayfarers semiotics trust fund ugh, venmo plaid skateboard blog kogi austin +1 helvetica. Slow-carb four dollar toast craft beer poutine authentic typewriter, kinfolk VHS crucifix mustache mumblecore. Echo park ugh single-origin coffee, aesthetic trust fund schlitz YOLO occupy pug pop-up listicle. Portland bespoke poutine twee four dollar toast. Bicycle rights man bun heirloom polaroid, banjo schlitz brooklyn poutine cliche helvetica meditation venmo. Offal sartorial ugh, small batch put a bird on it pug green juice tumblr. 8-bit literally keffiyeh offal master cleanse poutine.

Chambray kale chips dreamcatcher migas pitchfork semiotics. Marfa narwhal bitters post-ironic, dreamcatcher vinyl kickstarter humblebrag. Craft beer kogi trust fund gentrify tattooed. Tilde heirloom cray, wolf banh mi mixtape chia tumblr chillwave next level. Selvage thundercats swag cold-pressed brooklyn squid +1, mlkshk hammock locavore biodiesel. Kitsch meditation selvage fap freegan roof party semiotics, direct trade leggings 3 wolf moon. Lumbersexual helvetica vinyl waistcoat, try-hard iPhone beard small batch gentrify single-origin coffee kitsch trust fund.")


Article.create(title: "generated through seed.rb", content: "Wayfarers semiotics trust fund ugh, venmo plaid skateboard blog kogi austin +1 helvetica. Slow-carb four dollar toast craft beer poutine authentic typewriter, kinfolk VHS crucifix mustache mumblecore. Echo park ugh single-origin coffee, aesthetic trust fund schlitz YOLO occupy pug pop-up listicle. Portland bespoke poutine twee four dollar toast. Bicycle rights man bun heirloom polaroid, banjo schlitz brooklyn poutine cliche helvetica meditation venmo. Offal sartorial ugh, small batch put a bird on it pug green juice tumblr. 8-bit literally keffiyeh offal master cleanse poutine.

Chambray kale chips dreamcatcher migas pitchfork semiotics. Marfa narwhal bitters post-ironic, dreamcatcher vinyl kickstarter humblebrag. Craft beer kogi trust fund gentrify tattooed. Tilde heirloom cray, wolf banh mi mixtape chia tumblr chillwave next level. Selvage thundercats swag cold-pressed brooklyn squid +1, mlkshk hammock locavore biodiesel. Kitsch meditation selvage fap freegan roof party semiotics, direct trade leggings 3 wolf moon. Lumbersexual helvetica vinyl waistcoat, try-hard iPhone beard small batch gentrify single-origin coffee kitsch trust fund.")


Article.create(title: "generated through seed.rb", content: "Wayfarers semiotics trust fund ugh, venmo plaid skateboard blog kogi austin +1 helvetica. Slow-carb four dollar toast craft beer poutine authentic typewriter, kinfolk VHS crucifix mustache mumblecore. Echo park ugh single-origin coffee, aesthetic trust fund schlitz YOLO occupy pug pop-up listicle. Portland bespoke poutine twee four dollar toast. Bicycle rights man bun heirloom polaroid, banjo schlitz brooklyn poutine cliche helvetica meditation venmo. Offal sartorial ugh, small batch put a bird on it pug green juice tumblr. 8-bit literally keffiyeh offal master cleanse poutine.

Chambray kale chips dreamcatcher migas pitchfork semiotics. Marfa narwhal bitters post-ironic, dreamcatcher vinyl kickstarter humblebrag. Craft beer kogi trust fund gentrify tattooed. Tilde heirloom cray, wolf banh mi mixtape chia tumblr chillwave next level. Selvage thundercats swag cold-pressed brooklyn squid +1, mlkshk hammock locavore biodiesel. Kitsch meditation selvage fap freegan roof party semiotics, direct trade leggings 3 wolf moon. Lumbersexual helvetica vinyl waistcoat, try-hard iPhone beard small batch gentrify single-origin coffee kitsch trust fund.")


Article.create(title: "generated through seed.rb", content: "Wayfarers semiotics trust fund ugh, venmo plaid skateboard blog kogi austin +1 helvetica. Slow-carb four dollar toast craft beer poutine authentic typewriter, kinfolk VHS crucifix mustache mumblecore. Echo park ugh single-origin coffee, aesthetic trust fund schlitz YOLO occupy pug pop-up listicle. Portland bespoke poutine twee four dollar toast. Bicycle rights man bun heirloom polaroid, banjo schlitz brooklyn poutine cliche helvetica meditation venmo. Offal sartorial ugh, small batch put a bird on it pug green juice tumblr. 8-bit literally keffiyeh offal master cleanse poutine.

Chambray kale chips dreamcatcher migas pitchfork semiotics. Marfa narwhal bitters post-ironic, dreamcatcher vinyl kickstarter humblebrag. Craft beer kogi trust fund gentrify tattooed. Tilde heirloom cray, wolf banh mi mixtape chia tumblr chillwave next level. Selvage thundercats swag cold-pressed brooklyn squid +1, mlkshk hammock locavore biodiesel. Kitsch meditation selvage fap freegan roof party semiotics, direct trade leggings 3 wolf moon. Lumbersexual helvetica vinyl waistcoat, try-hard iPhone beard small batch gentrify single-origin coffee kitsch trust fund.")


Article.create(title: "generated through seed.rb", content: "Wayfarers semiotics trust fund ugh, venmo plaid skateboard blog kogi austin +1 helvetica. Slow-carb four dollar toast craft beer poutine authentic typewriter, kinfolk VHS crucifix mustache mumblecore. Echo park ugh single-origin coffee, aesthetic trust fund schlitz YOLO occupy pug pop-up listicle. Portland bespoke poutine twee four dollar toast. Bicycle rights man bun heirloom polaroid, banjo schlitz brooklyn poutine cliche helvetica meditation venmo. Offal sartorial ugh, small batch put a bird on it pug green juice tumblr. 8-bit literally keffiyeh offal master cleanse poutine.

Chambray kale chips dreamcatcher migas pitchfork semiotics. Marfa narwhal bitters post-ironic, dreamcatcher vinyl kickstarter humblebrag. Craft beer kogi trust fund gentrify tattooed. Tilde heirloom cray, wolf banh mi mixtape chia tumblr chillwave next level. Selvage thundercats swag cold-pressed brooklyn squid +1, mlkshk hammock locavore biodiesel. Kitsch meditation selvage fap freegan roof party semiotics, direct trade leggings 3 wolf moon. Lumbersexual helvetica vinyl waistcoat, try-hard iPhone beard small batch gentrify single-origin coffee kitsch trust fund.")


Article.create(title: "generated through seed.rb", content: "Wayfarers semiotics trust fund ugh, venmo plaid skateboard blog kogi austin +1 helvetica. Slow-carb four dollar toast craft beer poutine authentic typewriter, kinfolk VHS crucifix mustache mumblecore. Echo park ugh single-origin coffee, aesthetic trust fund schlitz YOLO occupy pug pop-up listicle. Portland bespoke poutine twee four dollar toast. Bicycle rights man bun heirloom polaroid, banjo schlitz brooklyn poutine cliche helvetica meditation venmo. Offal sartorial ugh, small batch put a bird on it pug green juice tumblr. 8-bit literally keffiyeh offal master cleanse poutine.

Chambray kale chips dreamcatcher migas pitchfork semiotics. Marfa narwhal bitters post-ironic, dreamcatcher vinyl kickstarter humblebrag. Craft beer kogi trust fund gentrify tattooed. Tilde heirloom cray, wolf banh mi mixtape chia tumblr chillwave next level. Selvage thundercats swag cold-pressed brooklyn squid +1, mlkshk hammock locavore biodiesel. Kitsch meditation selvage fap freegan roof party semiotics, direct trade leggings 3 wolf moon. Lumbersexual helvetica vinyl waistcoat, try-hard iPhone beard small batch gentrify single-origin coffee kitsch trust fund.")


Article.create(title: "generated through seed.rb", content: "Wayfarers semiotics trust fund ugh, venmo plaid skateboard blog kogi austin +1 helvetica. Slow-carb four dollar toast craft beer poutine authentic typewriter, kinfolk VHS crucifix mustache mumblecore. Echo park ugh single-origin coffee, aesthetic trust fund schlitz YOLO occupy pug pop-up listicle. Portland bespoke poutine twee four dollar toast. Bicycle rights man bun heirloom polaroid, banjo schlitz brooklyn poutine cliche helvetica meditation venmo. Offal sartorial ugh, small batch put a bird on it pug green juice tumblr. 8-bit literally keffiyeh offal master cleanse poutine.

Chambray kale chips dreamcatcher migas pitchfork semiotics. Marfa narwhal bitters post-ironic, dreamcatcher vinyl kickstarter humblebrag. Craft beer kogi trust fund gentrify tattooed. Tilde heirloom cray, wolf banh mi mixtape chia tumblr chillwave next level. Selvage thundercats swag cold-pressed brooklyn squid +1, mlkshk hammock locavore biodiesel. Kitsch meditation selvage fap freegan roof party semiotics, direct trade leggings 3 wolf moon. Lumbersexual helvetica vinyl waistcoat, try-hard iPhone beard small batch gentrify single-origin coffee kitsch trust fund.")


Article.create(title: "generated through seed.rb", content: "Wayfarers semiotics trust fund ugh, venmo plaid skateboard blog kogi austin +1 helvetica. Slow-carb four dollar toast craft beer poutine authentic typewriter, kinfolk VHS crucifix mustache mumblecore. Echo park ugh single-origin coffee, aesthetic trust fund schlitz YOLO occupy pug pop-up listicle. Portland bespoke poutine twee four dollar toast. Bicycle rights man bun heirloom polaroid, banjo schlitz brooklyn poutine cliche helvetica meditation venmo. Offal sartorial ugh, small batch put a bird on it pug green juice tumblr. 8-bit literally keffiyeh offal master cleanse poutine.

Chambray kale chips dreamcatcher migas pitchfork semiotics. Marfa narwhal bitters post-ironic, dreamcatcher vinyl kickstarter humblebrag. Craft beer kogi trust fund gentrify tattooed. Tilde heirloom cray, wolf banh mi mixtape chia tumblr chillwave next level. Selvage thundercats swag cold-pressed brooklyn squid +1, mlkshk hammock locavore biodiesel. Kitsch meditation selvage fap freegan roof party semiotics, direct trade leggings 3 wolf moon. Lumbersexual helvetica vinyl waistcoat, try-hard iPhone beard small batch gentrify single-origin coffee kitsch trust fund.")


Article.create(title: "generated through seed.rb", content: "Wayfarers semiotics trust fund ugh, venmo plaid skateboard blog kogi austin +1 helvetica. Slow-carb four dollar toast craft beer poutine authentic typewriter, kinfolk VHS crucifix mustache mumblecore. Echo park ugh single-origin coffee, aesthetic trust fund schlitz YOLO occupy pug pop-up listicle. Portland bespoke poutine twee four dollar toast. Bicycle rights man bun heirloom polaroid, banjo schlitz brooklyn poutine cliche helvetica meditation venmo. Offal sartorial ugh, small batch put a bird on it pug green juice tumblr. 8-bit literally keffiyeh offal master cleanse poutine.

Chambray kale chips dreamcatcher migas pitchfork semiotics. Marfa narwhal bitters post-ironic, dreamcatcher vinyl kickstarter humblebrag. Craft beer kogi trust fund gentrify tattooed. Tilde heirloom cray, wolf banh mi mixtape chia tumblr chillwave next level. Selvage thundercats swag cold-pressed brooklyn squid +1, mlkshk hammock locavore biodiesel. Kitsch meditation selvage fap freegan roof party semiotics, direct trade leggings 3 wolf moon. Lumbersexual helvetica vinyl waistcoat, try-hard iPhone beard small batch gentrify single-origin coffee kitsch trust fund.")


Article.create(title: "generated through seed.rb", content: "Wayfarers semiotics trust fund ugh, venmo plaid skateboard blog kogi austin +1 helvetica. Slow-carb four dollar toast craft beer poutine authentic typewriter, kinfolk VHS crucifix mustache mumblecore. Echo park ugh single-origin coffee, aesthetic trust fund schlitz YOLO occupy pug pop-up listicle. Portland bespoke poutine twee four dollar toast. Bicycle rights man bun heirloom polaroid, banjo schlitz brooklyn poutine cliche helvetica meditation venmo. Offal sartorial ugh, small batch put a bird on it pug green juice tumblr. 8-bit literally keffiyeh offal master cleanse poutine.

Chambray kale chips dreamcatcher migas pitchfork semiotics. Marfa narwhal bitters post-ironic, dreamcatcher vinyl kickstarter humblebrag. Craft beer kogi trust fund gentrify tattooed. Tilde heirloom cray, wolf banh mi mixtape chia tumblr chillwave next level. Selvage thundercats swag cold-pressed brooklyn squid +1, mlkshk hammock locavore biodiesel. Kitsch meditation selvage fap freegan roof party semiotics, direct trade leggings 3 wolf moon. Lumbersexual helvetica vinyl waistcoat, try-hard iPhone beard small batch gentrify single-origin coffee kitsch trust fund.")


Article.create(title: "generated through seed.rb", content: "Wayfarers semiotics trust fund ugh, venmo plaid skateboard blog kogi austin +1 helvetica. Slow-carb four dollar toast craft beer poutine authentic typewriter, kinfolk VHS crucifix mustache mumblecore. Echo park ugh single-origin coffee, aesthetic trust fund schlitz YOLO occupy pug pop-up listicle. Portland bespoke poutine twee four dollar toast. Bicycle rights man bun heirloom polaroid, banjo schlitz brooklyn poutine cliche helvetica meditation venmo. Offal sartorial ugh, small batch put a bird on it pug green juice tumblr. 8-bit literally keffiyeh offal master cleanse poutine.

Chambray kale chips dreamcatcher migas pitchfork semiotics. Marfa narwhal bitters post-ironic, dreamcatcher vinyl kickstarter humblebrag. Craft beer kogi trust fund gentrify tattooed. Tilde heirloom cray, wolf banh mi mixtape chia tumblr chillwave next level. Selvage thundercats swag cold-pressed brooklyn squid +1, mlkshk hammock locavore biodiesel. Kitsch meditation selvage fap freegan roof party semiotics, direct trade leggings 3 wolf moon. Lumbersexual helvetica vinyl waistcoat, try-hard iPhone beard small batch gentrify single-origin coffee kitsch trust fund.")


Article.create(title: "generated through seed.rb", content: "Wayfarers semiotics trust fund ugh, venmo plaid skateboard blog kogi austin +1 helvetica. Slow-carb four dollar toast craft beer poutine authentic typewriter, kinfolk VHS crucifix mustache mumblecore. Echo park ugh single-origin coffee, aesthetic trust fund schlitz YOLO occupy pug pop-up listicle. Portland bespoke poutine twee four dollar toast. Bicycle rights man bun heirloom polaroid, banjo schlitz brooklyn poutine cliche helvetica meditation venmo. Offal sartorial ugh, small batch put a bird on it pug green juice tumblr. 8-bit literally keffiyeh offal master cleanse poutine.

Chambray kale chips dreamcatcher migas pitchfork semiotics. Marfa narwhal bitters post-ironic, dreamcatcher vinyl kickstarter humblebrag. Craft beer kogi trust fund gentrify tattooed. Tilde heirloom cray, wolf banh mi mixtape chia tumblr chillwave next level. Selvage thundercats swag cold-pressed brooklyn squid +1, mlkshk hammock locavore biodiesel. Kitsch meditation selvage fap freegan roof party semiotics, direct trade leggings 3 wolf moon. Lumbersexual helvetica vinyl waistcoat, try-hard iPhone beard small batch gentrify single-origin coffee kitsch trust fund.")


Article.create(title: "generated through seed.rb", content: "Wayfarers semiotics trust fund ugh, venmo plaid skateboard blog kogi austin +1 helvetica. Slow-carb four dollar toast craft beer poutine authentic typewriter, kinfolk VHS crucifix mustache mumblecore. Echo park ugh single-origin coffee, aesthetic trust fund schlitz YOLO occupy pug pop-up listicle. Portland bespoke poutine twee four dollar toast. Bicycle rights man bun heirloom polaroid, banjo schlitz brooklyn poutine cliche helvetica meditation venmo. Offal sartorial ugh, small batch put a bird on it pug green juice tumblr. 8-bit literally keffiyeh offal master cleanse poutine.

Chambray kale chips dreamcatcher migas pitchfork semiotics. Marfa narwhal bitters post-ironic, dreamcatcher vinyl kickstarter humblebrag. Craft beer kogi trust fund gentrify tattooed. Tilde heirloom cray, wolf banh mi mixtape chia tumblr chillwave next level. Selvage thundercats swag cold-pressed brooklyn squid +1, mlkshk hammock locavore biodiesel. Kitsch meditation selvage fap freegan roof party semiotics, direct trade leggings 3 wolf moon. Lumbersexual helvetica vinyl waistcoat, try-hard iPhone beard small batch gentrify single-origin coffee kitsch trust fund.")